'use-client'
import React, { useEffect, useState } from "react";

import { InfiniteMovingCards } from "./ui/infinite-movingcards";
function InfiniteCards() {
     
  const testimonials = [
    {
        quote: "The rise of quantum computing promises to tackle complex computational problems that are currently intractable for classical computers, such as simulating molecular interactions and optimizing financial portfolios.",
        name: "Michelle Simmons",
        title: "Quantum Physicist"
    },
    {
        quote: "Deep learning, a subset of machine learning, has enabled remarkable advancements in artificial intelligence, leading to breakthroughs in natural language processing, computer vision, and autonomous driving.",
        name: "Yann LeCun",
        title: "Chief AI Scientist at Facebook"
    },
    {
        quote: "The convergence of biotechnology and computing, known as bioinformatics, is revolutionizing fields such as genomics, personalized medicine, and drug discovery, leading to more effective treatments for various diseases.",
        name: "Frances Arnold",
        title: "Chemical Engineer and Nobel Laureate"
    },
    {
        quote: "Augmented reality (AR) and virtual reality (VR) technologies are reshaping how we interact with digital content, offering immersive experiences in gaming, education, architecture, and healthcare.",
        name: "Mark Zuckerberg",
        title: "CEO of Meta Platforms, Inc. (formerly Facebook)"
    },
    {
        quote: "The exponential growth of data generated by devices, sensors, and social media has led to the emergence of big data analytics, enabling organizations to derive valuable insights and make data-driven decisions.",
        name: "Tim Berners-Lee",
        title: "Inventor of the World Wide Web"
    },
    {
        quote: "Cybersecurity remains a critical concern in the digital age, with cyber attacks becoming more sophisticated and frequent, highlighting the need for robust security measures and cyber defense strategies.",
        name: "Bruce Schneier",
        title: "Cybersecurity Expert and Author"
    },
    {
        quote: "Advancements in robotics and automation are transforming industries such as manufacturing, logistics, and healthcare, enhancing productivity, efficiency, and safety in various operations.",
        name: "Rodney Brooks",
        title: "Robotics Engineer and Co-founder of iRobot"
    },
    {
        quote: "The democratization of technology through open-source software and collaborative platforms has empowered individuals and communities to innovate, share knowledge, and solve global challenges.",
        name: "Linus Torvalds",
        title: "Creator of Linux Kernel"
    },
    {
        quote: "The Internet of Things (IoT) ecosystem is expanding rapidly, connecting billions of devices and enabling smart applications in smart homes, cities, agriculture, and industrial automation.",
        name: "Vint Cerf",
        title: "Co-inventor of the Internet Protocols"
    },
    {
        quote: "Edge computing, by processing data closer to the source, reduces latency and bandwidth usage, enabling real-time analytics, IoT applications, and immersive experiences in remote locations.",
        name: "Satya Nadella",
        title: "CEO of Microsoft Corporation"
    },
    {
        quote: "The ethical implications of artificial intelligence, including biases in algorithms, privacy concerns, and job displacement, underscore the importance of responsible AI development and governance.",
        name: "Fei-Fei Li",
        title: "Computer Scientist and AI Researcher"
    },
    {
        quote: "Blockchain technology has the potential to revolutionize various industries by providing secure and transparent decentralized systems for transactions, digital identity management, and supply chain tracking.",
        name: "Vitalik Buterin",
        title: "Co-founder of Ethereum"
    },
    {
      quote: "The advent of 5G technology promises ultra-fast internet speeds and low latency, paving the way for innovations in autonomous vehicles, remote surgeries, and immersive virtual reality experiences.",
      name: "Ericsson Mobility Report",
      title: ""
  },
  {
      quote: "Advancements in natural language processing have led to the development of chatbots and virtual assistants capable of understanding and responding to human language, enhancing customer service and user experience.",
      name: "Gartner",
      title: ""
  },
  {
      quote: "The rise of DevOps practices, emphasizing collaboration between development and operations teams, has led to faster software delivery, improved deployment frequency, and higher quality software products.",
      name: "State of DevOps Report",
      title: ""
  },
  {
      quote: "Cloud computing has democratized access to computing resources, enabling startups and enterprises alike to scale infrastructure dynamically and reduce operational costs through pay-as-you-go pricing models.",
      name: "Amazon Web Services",
      title: ""
  },
  {
      quote: "The concept of microservices architecture advocates building software applications as a collection of small, independently deployable services, fostering agility, scalability, and ease of maintenance.",
      name: "Martin Fowler",
      title: ""
  },
  {
      quote: "The proliferation of e-commerce platforms and digital payment systems has transformed the retail landscape, offering consumers convenience, choice, and personalized shopping experiences.",
      name: "Statista",
      title: ""
  },
  {
      quote: "Graph databases, which represent data as interconnected nodes and edges, excel in modeling complex relationships and are increasingly used in applications such as social networks, recommendation engines, and fraud detection.",
      name: "Neo4j",
      title: ""
  },
  {
      quote: "The integration of machine learning algorithms in image recognition has fueled advancements in medical imaging, enabling early disease detection, personalized treatment plans, and improved patient outcomes.",
      name: "Nature Medicine",
      title: ""
  },
  {
      quote: "Robotic process automation (RPA) streamlines repetitive tasks by automating workflows, reducing human error, and freeing up human resources for more creative and strategic endeavors.",
      name: "Forrester",
      title: ""
  },
  {
      quote: "Continuous integration and continuous deployment (CI/CD) practices automate the software delivery pipeline, enabling faster releases, shorter feedback cycles, and greater responsiveness to customer needs.",
      name: "Jenkins",
      title: ""
  }
];

  return (
    <div className="h-[40rem] dark:bg-black dark:bg-grid-white/[0.2] flex flex-col items-center justify-center overflow-hidden">
        <h2 className="text-3xl font-bold text-center mb-8 border-b-zinc-10">Ever Thought?</h2>
     <div className="flex justify-center w-full overflow-hiddden px-4 sm:px-6 lg:px-8">
     <div className="w-full max-w-6xl">
      <InfiniteMovingCards
        items={testimonials}
        direction="right"
        speed="slow"
      /></div></div>
    </div>
  )
}

export default InfiniteCards
